apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 455646290812.dkr.ecr.ap-south-1.amazonaws.com/yt-auth-service:latest
        imagePullPolicy: Always
        env:
        # 1. The Correct Service Registry endpoint location
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        
        # 2. FORCE Spring to read the relaxed property matching layout
        - name: SPRING_CLOUD_CLIENT_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        # 3. Force Eureka to map the address metadata straight to the raw IP value
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AUTH_DB_URL
          valueFrom:
            configMapKeyRef:
              name: global-db-config
              key: auth_db_url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  ports:
  - port: 80
    targetPort: 8080 
    protocol: TCP
  selector:
    app: auth-service
  type: ClusterIP
