apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: default

spec:
  ports:
    - port: 8761
      targetPort: 8761

  type: ClusterIP

  selector:
    app: service-registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: service-registry

  template:
    metadata:
      labels:
        app: service-registry

      annotations:
        oneagent.dynatrace.com/inject: "true"

    spec:
      containers:
      - name: service-registry
        image: 455646290812.dkr.ecr.ap-south-1.amazonaws.com/service-registry:latest
        ports:
        - containerPort: 8761

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        env:
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"

        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"

        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
