apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  namespace: default
  labels:
    app: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
      annotations:
        oneagent.dynatrace.com/inject: "true"
    spec:
      containers:
      - name: video-service
        image: 455646290812.dkr.ecr.ap-south-1.amazonaws.com/yt-video-service:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "video-service"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "80"
        - name: VIDEO_DB_URL
          valueFrom:
            configMapKeyRef:
              name: global-db-config
              key: video_db_url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: password
        - name: AWS_REGION
          value: "ap-south-1"
        - name: AWS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: global-db-config
              key: s3_bucket_name
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: default
  labels:
    app: video-service
spec:
  ports:
  - port: 80
    targetPort: 8082 
    protocol: TCP
  selector:
    app: video-service
  type: ClusterIP
